### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by linusg** [ekzhang/rustpad#1]
A dark mode, possibly based on the [`prefers-color-scheme`](https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme) media query, would be nice! Given that this uses Monaco, leveraging some existing theme should be fairly straightforward.

**Comment by ekzhang** [comment]
Absolutely, thanks for the suggestion. I'm also a VS Code dark theme user! Happy to take PRs if anyone is interested in implementing this.

**Comment by SphericalKat** [comment]
Hi, I just made a PR for dark mode, please let me know if you want any changes :)
