### ISSUE TITLE
Any plans of implementing text and voice chats?

### ISSUE THREAD

**Issue by nzour** [ekzhang/rustpad#11]

**Comment by ekzhang** [comment]
That seems like an interesting and pretty simple feature. Text chat would be pretty simple. As for voice chat, do you have a free service in mind that Rustpad could integrate with?

**Comment by nzour** [comment]
> do you have a free service in mind that Rustpad could integrate with
Unfortunately no, I don't.

> Text chat would be pretty simple
You think of implementing this feature by yourself or integrate with external free service?

**Comment by curiouswala** [comment]
https://github.com/feross/simple-peer#usage something like this can be used for a p2p voice/video chat.

**Comment by ashim-k-saha** [comment]
https://github.com/webrtc-rs/webrtc
