### ISSUE TITLE
Third-party websocket client

### ISSUE THREAD

**Issue by curiouswala** [ekzhang/rustpad#12]
I would love to use rustpad for my hardware live coding project.
Is it possible to connect a third-party client via WebSocket to rustpad?
If you can point me to any examples or resources it would be great.

Thank you.

**Comment by curiouswala** [comment]
I was able to connect a client to this address and get WebSocket updates.

wss://rustpad.io/api/socket/#####

this is what I get at first connection

  {
    "id": 0,
    "operation": [
      "p"
    ]
  },
  {
    "id": 0,
    "operation": [
      1,
      "rin"
    ]
  },
  {
    "id": 0,
    "operation": [
      4,
      "t"
    ]
  },
  
Is there a way to get the full text file in a single request?

**Comment by ekzhang** [comment]
Yep, that's right. The protocol is documented and specified in the backend code at `rustpad-server/src/rustpad.rs`. See the `ClientMsg` and `ServerMsg` data types, respectively. These are serialized/deserialized to JSON.

If you want to get the full text file, you can send an HTTP GET request to `/api/text/[id]`.

**Comment by ekzhang** [comment]
If you want to build a separate client using this WebSocket server implementation, you will need to establish a WebSocket connection to `/api/socket/[id]`, then mimic the behavior of the web client.

- Whenever the user makes a change to the document, you should represent that change by an `OperationSeq` and send it in a `Edit` message to the server, over WebSocket.
- While that's being sent, buffer all remaining changes, until acknowledgement from the server is received.
- Whenever a remote change is received from the server, run operational transformation on it and apply it to your textarea. Transform any buffered or pending changes.
- (Optionally, support messages like editor language changes, user presence (entering/leaving), cursor positions, etc.)

Most of the client-side logic for this in the Rustpad's Monaco editor implementation can be found in `src/rustpad.ts`.

**Comment by curiouswala** [comment]
Perfect! 
One last question, Have you looked into making a portable executable version of rustpad? 
Thank you.

**Comment by ekzhang** [comment]
No, unfortunately not. I don't have the experience or interest in compiling executables for different platforms, then distributing them.

**Comment by curiouswala** [comment]
Fair enough. Thank you for all the help.
