### ISSUE TITLE
Rustpad breaks when adding Emoji

### ISSUE THREAD

**Issue by TheForcer** [ekzhang/rustpad#14]
Hi, I have been using Rustpad for a little while now using a self-deployed instance. While collaborating with a few friends on a document today, we found out that inserting unicode emoji (e.g. by using the "Windows-Key"+"." shortcut, or pasting from somewhere else) breaks the document. Rustpad then tries reconnecting, fails and throws the "Desynchronized" error message.

The document cannot be edited afterwards anymore, so the existing content needs to be migrated to a new rustpad (minus the emoji). I noticed the same behaviour on the rustpad.io instance.

Would be great if you could take a look at this. Unfortunately I'm not of much help regarding Rust or JS. Thanks :)

**Comment by ekzhang** [comment]
Huh, that's not good. Thanks for catching. I can confirm this doesn't work for me either.
