### ISSUE TITLE
Connecting to server issue when using reverse proxy

### ISSUE THREAD

**Issue by AzamServer** [ekzhang/rustpad#17]
I'm using a reverse proxy for SSL and when I open rustpad, it always tell me that it's connecting to server, which it never does. Any help?

Using NGINX for reverse proxy
Using Cloudflare for SSL Provider

**Comment by orhun** [comment]
Hey, check out my example configuration: https://github.com/ekzhang/rustpad/issues/2#issuecomment-855458489

Maybe you forgot to configure the proxy headers.

**Comment by AzamServer** [comment]
> Hey, check out my example configuration: https://github.com/ekzhang/rustpad/issues/2#issuecomment-855458489
> 
> 
> 
> Maybe you forgot to configure the proxy headers.

That worked! Thanks so much!
