### ISSUE TITLE
Output logs to Docker

### ISSUE THREAD

**Issue by huiguang-liang** [ekzhang/rustpad#22]
Apologies if I'm barking up the wrong tree - but for some reason when I'm running this in a Docker container, I can't see any log messages in `/var/log/docker.log` relating to rustpad. The Rustpad web app itself works fine.

Context: I'm running the dockerized image straight from [https://hub.docker.com/r/ekzhang/rustpad](https://hub.docker.com/r/ekzhang/rustpad). The environment is Unraid v6.9.2 with Docker v20.10.5

**Comment by ekzhang** [comment]
If you're looking for log messages, have you tried setting the `RUST_LOG` environment variable to the desired level? For example, you could try `docker run ... -e RUST_LOG=info`.

**Comment by orhun** [comment]
It is also good to point out that if you're running a `rustpad` container with `-d` (`--detach`) option, you can view the logs via `docker logs <container_name>`.

**Comment by huiguang-liang** [comment]
Thank you both. This is my first foray into Rust and Docker containers so I'm missing all the intricacies and nuances. Cheers.
