### ISSUE TITLE
Set <Editor/> fontSize as configurable or docker environment parameter

### ISSUE THREAD

**Issue by huiguang-liang** [ekzhang/rustpad#23]
At present, for HiDPI displays, the editor fontsize is a little too small. After inspecting the source I see that the fontSize is hardcoded. 

```
<Editor
    theme={darkMode ? "vs-dark" : "vs"}
    language={language}
    options={{
        automaticLayout: true,
        fontSize: 13,
    }}
    onMount={(editor) => setEditor(editor)}
/>
```
Is it possible to expose this `fontSize` setting as a Docker environment variable?

**Comment by ekzhang** [comment]
Would it be sufficient to increase the zoom level of your browser?

If this isn't enough, we can maybe add some client configuration to let the user change the font size from within the webapp, but I don't think this would be appropriate to configure on the server side.

**Comment by huiguang-liang** [comment]
Yes of course, you're right, a client-side configuration would be most appropriate. I don't know enough about web app architectures so please excuse my inability to ask the 'right' questions. I'll raise the client-side UI features I'd like to see in another issue.
