### ISSUE TITLE
Client-Side UI Configuration Options

### ISSUE THREAD

**Issue by huiguang-liang** [ekzhang/rustpad#24]
Hello team, excellent work on this, it fits my needs almost perfectly. There are three configuration options I'd like to see at client side that would complete this dream app.

1. As a user, l'd like to be able to change the <Editor/> `fontSize`.
2. As a user, l'd like to be able to change the <Editor/> `fontFamily` (in particular, [JetBrains Mono](https://fonts.google.com/specimen/JetBrains+Mono)),
3. As a user, I'd like to be able to select other color themes (in particular, [Dracula](https://draculatheme.com/visual-studio-code)).

Bonus brownie points:
1. If you could write some documentation on hub.docker.com so that noobs like me can follow. These folks, for e.g., write great documentation: [linuxserver.io](https://hub.docker.com/u/linuxserver)

**Comment by ekzhang** [comment]
Thanks for the suggestions. Unfortunately, this is likely not going to be implemented. Number 1 can be adjusted proportionally with just browser zoom level; number 2 is subject to licensing issues; and number 3 is out of scope (if we support one theme, do we support 100 themes?).
