### ISSUE TITLE
How do I compile and build a production docker instance?

### ISSUE THREAD

**Issue by huiguang-liang** [ekzhang/rustpad#25]
Given my very limited and sketchy knowledge of docker and rust, I'm not 100% sure where and which flags I can set to compile and build a docker image that is tagged production instead of a dev instance (its showing as "development" in the bottom left hand footer).

A little documentation on which parameters or flags that I can use as, say, a Docker environment variable would be lovely and much appreciated. Cheers.

**Comment by ekzhang** [comment]
Hey, you can use the prebuilt Docker image at https://hub.docker.com/r/ekzhang/rustpad.

If you would like to build your own image with a tagged hash like the official image, you should set the GITHUB_SHA build arg to the correct hash. This is done by our CI pipeline in .github/workflows.
