### ISSUE TITLE
rust playground integration

### ISSUE THREAD

**Issue by lucaszanella** [ekzhang/rustpad#3]
this would be so cool with rust playground integration

thank you very much

**Comment by ekzhang** [comment]
Would be nice, but this is a general-purpose editor. Probably the strategy would be the other way around, i.e., adding collaborative editing support to Rust Playground. That's an entirely new project in itself though.

I'm not sure if the Rust Playground people would want the additional complexity of adding such a feature, but it's probably possible to fork it if you'd like. Not something that I will work on right now though.
