### ISSUE TITLE
arm64 (aarch64) Support

### ISSUE THREAD

**Issue by 9SMTM6** [ekzhang/rustpad#31]
Hey!

Given the technologies used in this project, and that I already run code-server just fine on it, this should be running just fine on an Raspberry-Pi (at least versions >=3).

With that in mind, and seeing that the official Docker-Image just works on amd64, I cloned the repository and tried around a bit.

Btw, from what I've seen its a nice code-basis. The tsx-Code (the JS part of the frontend) could use a few folders but otherwise real nice, insofar as I'm a good judge of that.

Well, I saw some good and some problematic stuff, but the problematic stuff should be possible to work around. The good stuff is that `rustpad-server` builds just fine.

The problem is that wasm-pack seems to REALLY not like arm64. I was able to fix some issues by installing wasm-pack via cargo install instead of the install script, and switching from rust:alpine with musl to the debian based rust:latest. After this (and loong build-times, even on my raspi 4 with an SSD, but thats Rust) it failed because of another binary wasm-pack looking for AFTER most of the compilation of the project - not `wasm-pack` but your `rustpad-server`-, `wasm-opt`. Now, I could fix that too, and I think it should be fine after this - I guess this does some kind of link-time-optimization? -, but I'm unsure what influence that might have on performance, and given how long it took to get here to start, and that this should be avoidable (see later), I think it would be great to solve this on an project-level.

Because given that the purpose of that step is to generate some architecture-independent wasm-"binary", and Rusts excellent cross-compilation support, I'm sure there is a way to just create 

1) the architecture-independent wasm, js etc artifacts
2) and the architecture-dependent binary

In your pipeline and either at least distribute these artifacts, or better yet find a way to make the pipeline build an arm64 docker-image that also gets distributed via docker-hub.

After all once you have these artifacts all thats left to do is copy these into the image, switch the user and declare the entrypoint, all that in a simple "scratch" container.

Now, the reason I post this here, and don't just do it and make a PR, is that

1) I have no experience with docker-multiarch etc, so if someone has some comments on this/wants to help I'd love that
2) This would influence the pipeline quite a bit, and I wanted to check with you that such changes would even be accepted/ generally hear what your feeling is about all this.

Sam.

**Comment by 9SMTM6** [comment]
Huh. wasm-opt should not be used anyways according to [this](https://bytecodealliance.github.io/cargo-wasi/wasm-opt.html#disabled-when-wasm-bindgen-is-used). Maybe thats old info or more likely wasm-pack installs wasm-opt in any situation? 

I'll try whether I can get it running without wasm-opt, but this will take well into the night for me since it will break every docker cache layer, and I've got other stuff I need to prioritize, so It might take some time until I report back whether that builds on raspi. Given these build-times it sure would still be nice to have this distributed over docker-hub.

**Comment by ekzhang** [comment]
Hi Sam, thanks for looking into this! Always appreciate people interested in porting to other platforms. I think you ran into just about the same slew of issues that I did when I was trying to support arm64 about a month ago and gave up at the time, see #29. :)

Thanks for the advice, and I agree that the WASM / frontend portion of the app is not dependent on platform, only the binary matters. So given that the WASM toolchain is the part that doesn't support arm64 right now, do you know if Docker supports just changing the `wasm` and `backend` build stages to specify `x86_64` platform? I found a [blog post](https://blog.asksven.io/posts/docker-build-for-multiple-architectures/) online that suggests you might be able to just prepend `x86_64:` to both stages, and then it would simply work. Maybe I'll briefly try this and see if GitHub Actions likes it.

Agree that it would be nice to have images on Docker Hub! Honestly, Docker is not great as a way of shipping software, but it's easier than manually setting up distribution for cross-platform binaries!

**Comment by 9SMTM6** [comment]
Oops on the title, thanks for that:-P

Thanks for the fast feedback. Interesting read, that Blog, I've never used Qemu or docker-multiarch before, so I had to take some time.

I don't entirely understand how the story with the Qemu binary works. I THINK sure your suggestion works, I'm also not sure what you're suggesting exactly.

But a combination of your and mine thoughts might be the cleanest best approach, even if it might not be a big difference or what you meant.

Yes, I think the WASM and other web-artifacts should work platform-independent. But what I think you have missed in my comments is "the excellent cross-compilation capabilities of rustc". So even the compilation of `rustpad-server` can be done in an x64 docker build, with the right `--target` flag for rustc (and the installation of the right toolchains) you can also compile the arm binary without having to get the combination of qemu binary and image right.

Then, because, as that blog mentions, theres no 'RUN' directives in the last stage, we should probably get away with just the `amd64/` qualifier in front of `scratch`.

In the end, thinking about it again, probably doesn't make much of a difference. Either provide the qemu-binary and image-qualifier with build-args or the target-triple and the image-qualifier. But its at least for me somewhat easier to reason about the last.

**Comment by 9SMTM6** [comment]
Ah, yes, It seems I overcompilcated how hard it seems to be to do multiarch with these github-actions.

Well, if that works this would be even better.

Anyways, time for me to sleep.

**Comment by ekzhang** [comment]
Fingers crossed that in 2 hours, when the build job finishes, you'll be able to pull this from your Raspberry Pi. :)

**Comment by ekzhang** [comment]
It works :)

![image](https://user-images.githubusercontent.com/7550632/147525290-ef637c43-2460-474f-8c4a-f6672cc29a3b.png)

**Comment by 9SMTM6** [comment]
Jup, just tested it, it also executes just fine on the Raspberry.

Btw, regarding the build-times, I could imagine that my approach is faster, since it doesn't do emulation (which, from my understanding, your approach does, perhaps even with 2 layers, in the arm64 pipeline with the amd64 image). Also one could reuse artifacts. Depending on if docker layer caching works at all in your pipeline, and if its smart enough, it might even solve that reuse of artifacts issue for us.

It would require more adjustments to the Dockerfile (installing the arm64 toolchain, passing the toolchain to cargo via docker build argument, as well as passing the architecture of the scratch image via another docker build argument), and another step where we combine the images for the different architectures with docker manifest (as written in the blog you mentioned).

So not sure if that would be worth it for you, but I could make a PR that tries to do that to reduce build-times.

In any case, thanks for the image and all!

**Comment by ekzhang** [comment]
Thanks for the suggestion and offer! Unfortunately I want to keep allowing people to build the image themselves using `docker build -t rustpad .` if possible (since this has been the process for the past 6 months), so we might have to stick with this. :)
