### ISSUE TITLE
FreeBASIC Syntax highlighting

### ISSUE THREAD

**Issue by c-sanchez** [ekzhang/rustpad#34]
Hi, please add FreeBASIC Syntax highlighting.
https://freebasic.net/

Maybe this help?
https://github.com/KDE/syntax-highlighting/blob/master/data/syntax/freebasic.xml

Btw thanks for making Rustpad, this is really awesome :D

**Comment by ekzhang** [comment]
Thanks for the feature request. You'll need to add FreeBASIC as a supported language to Monaco. See https://github.com/microsoft/monaco-editor/tree/main/src/basic-languages - perhaps create an issue there?
