### ISSUE TITLE
Ease-of-use: Upload and download of Files

### ISSUE THREAD

**Issue by 9SMTM6** [ekzhang/rustpad#36]
Hey, I've used this Application a bit now, and I've got a few ideas. 

As my Exams are coming up I will not be able to contribute much to these, but I wanted to record them here nonetheless.

First there were 2 things that I wondered about, that were already addressed, or likely out of scope, and that are persistent files/sessions (so it can work as a kind of pastebin) (it seems #6 addresses that), and multi-file workspaces are probably widely out of scope.

But I had another thought that should not be too hard to implement, and IMO would significantly increase ergonomics.

"File"-Upload and Download does not seem to be implemented, unless I missed it. The way I imagine it, is that one would be able to "Upload" a text-file via drag and drop, this would just paste in the content, and ideally also determine the Programming-language via file-extension. To download, I've seen websites that intercept the `Ctrl-S` command to save files (eg drawio). I'm not actually sure how they do it, but it appears there is a way, and that would be ideal IMAO.

Thanks, Sam.

**Comment by ekzhang** [comment]
Thanks for the bug report. Having a save button and drag-and-drop uploads seems like they would be good features.

**Comment by 9SMTM6** [comment]
My Exams will actually be over by the 12th of Feb, the ones that seem critical by the 8th. I might need some breathing room after that, but I would actually like too look into this after.

I do not have... to be honest any experience in Rust Backends, but I did want to get into it. Warp looks like a good choice, and I like your programming style, so this could be valuable to me.

I expect to be less stressed and thus more coherent by then, and as you know, I can have a few clever ideas at times, so I hope my contribution will be worthy;).

Just writing this here to let you know that someone will eventually look into this.

**Comment by 9SMTM6** [comment]
@hilaolu do you have an intended use-case? To me it seems a bit beyond the purpose of this application, especially considering that documents on here have limited TTL on default settings, and AFAIK you can't give them a "Name" but they will just have a random ID.

If @ekzhang wants to add that I'd be happy to. In my PR I've so far done without, just using the already present websocket, my changes are entirely limited to the frontend.

I've yet to hear from him on my PR, its been a while.
