### ISSUE TITLE
Bug/Discussion: Cursor-Position in collaborative coding

### ISSUE THREAD

**Issue by 9SMTM6** [ekzhang/rustpad#37]
When using this I've stumbled upon an issue. I'm not sure if my suggested fix is actually always a good idea, or how easy it would be to solve, so this should probably be discussed.

If multiple persons work in different areas of a file, this can lead to conflicts, when the person that is closer to the beginning of the file inserts/deletes newlines, or with both in a single line just when it enters anything.

Because this will not change the position of the cursor of the other person in the file, meaning its cursor will move in relation to the context the person was working on, since that context is indirectly moved by the other person.

This can be fairly disrupting, if one was currently writing something, it might be spread over multiple lines or be... interlaced with the past characters.

The fix would be to move the cursor accordingly, depending on its current position. If its on the same line and past the other cursor, it has to be moved forward, if its simply below, it has to be moved down, if its above or generally before the other cursor, it doesn't get influenced.

**Comment by 9SMTM6** [comment]
Perhaps a better way to reason about it is to place each cursor in relation to the cursor before, and just the first cursor in relation to the file-start.

That way the state would not be manipulated, and it would cut down on required logic and potential errors. Would be a potentially bigger change from the status quo though. Maybe it interacts better or worse with network delays etc, I don't know the way it works currently, also I'm tired.

**Comment by ekzhang** [comment]
> Because this will not change the position of the cursor of the other person in the file, meaning its cursor will move in relation to the context the person was working on, since that context is indirectly moved by the other person.

Thanks for the bug report. Unfortunately, I don't understand what you mean by this. Insertions of newlines are considered in the collaborative editing algorithm used by Rustpad, and they should not affect other users' changes. Could you clarify the issue, and either provide a minimal reproducible example or show a video of what you mean?

**Comment by 9SMTM6** [comment]
Sorry for the slow response. I've been incredibly busy.

This is embarrassing. I am unable to recreate this issue. It behaves exactly like I suggested as an improvement.

I could've sworn that it behaved erratic like that in one of my sessions, but me being me I did not validate it before going through this report process.

Sorry to take up your time and thanks for this well designed App!
