### ISSUE TITLE
Sidebar should hide on a narrow display

### ISSUE THREAD

**Issue by yuwash** [ekzhang/rustpad#38]
It seems like there’s currently no way to collapse the left-hand sidebar (dark mode, language etc.). It takes up a constant amount of width of the display, so on a narrow window (mobile phone or split screen) the remaining space for actually writing text gets very limited if existent at all… The possibility to hide it would also benefit people with wide displays as it removes visual clutter.

**Comment by ekzhang** [comment]
Thanks for the suggestion. Unfortunately we don't really support mobile devices, due to limitations of the Monaco text editor.

**Comment by yuwash** [comment]
Suggestion wasn’t strictly limited to mobile, but good to know anyway and thanks for the quick response
