### ISSUE TITLE
Mobile Responsive support?

### ISSUE THREAD

**Issue by hzhoanglee** [ekzhang/rustpad#39]
Hi, I really love your application because it's simplicity.
The application works great on large screen devices like computers and tablets. However, when I open it using my phone (iPhone 7), the left panel seem to cover all the screen that users like me can not see the text content.
Do you have any plan to add Mobile Responsive in the future?

Thank you and stay safe!

**Comment by orhun** [comment]
I think this was answered in https://github.com/ekzhang/rustpad/issues/38#issuecomment-1018022425

**Comment by hzhoanglee** [comment]
> I think this was answered in [#38 (comment)](https://github.com/ekzhang/rustpad/issues/38#issuecomment-1018022425)

Sorry that I didn't check that issue. Really thank you for your instant reply.
I am enjoying your application.

**Comment by orhun** [comment]
> Sorry that I didn't check that issue. Really thank you for your instant reply. I am enjoying your application.

All credit goes to @ekzhang, I'm just a stranger hanging around 🙂

**Comment by ekzhang** [comment]
Thanks @orhun! Also, if it's helpful as a reference, here's the issue from the Monaco side: https://github.com/microsoft/monaco-editor/issues/246 - I also think it would be really nice to have good mobile support but don't know what good support for code editing on mobile would really look like yet.
