### ISSUE TITLE
Read-only mode?

### ISSUE THREAD

**Issue by binarydad** [ekzhang/rustpad#40]
Not a bug, but a feature request. I LOVE the editor abilities of this, but would like the option to share it as read-only. I suppose an approach to having this work so that the author can still make changes, is perhaps a new link that references the original "tag", but is one that, when de-referenced, renders the code in a read-only console. 

Or, if it can generate a new link "tag", of which it's read only? Not sure how it's implemented internally but either way, I would love this option if considered. Thanks.

**Comment by ekzhang** [comment]
Hi, thanks for the message. That's an interesting idea, what would your intended use-case for a read-only code editor be?

**Comment by binarydad** [comment]
If I want to demo code changes to an audience that has no need to make (either intentionally or unintentionally) changes to the code. I may also want to write up a script, and send someone the link for them to view it later (they would have no need either to modify the code).

**Comment by ekzhang** [comment]
Thanks for telling me more about your use case! That sounds interesting and nice to have, though I'm not sure if it's worth the extra complexity in the application.

**Comment by karanbhangui** [comment]
Seems like streaming a code session or remote instruction could benefit from a read-only viewer mode.
