### ISSUE TITLE
Seeing two cursors when more than one user is connected 

### ISSUE THREAD

**Issue by gondar00** [ekzhang/rustpad#42]
Hi, 

I am seeing two cursors when more than one user is connected while typing

https://user-images.githubusercontent.com/12490590/153477906-5cd43c72-cb8c-47f6-af3a-4c5974a74c1c.mov

**Comment by orhun** [comment]
This sounds like an expected behavior if you meant seeing the cursor of the other user while typing simultaneously.

**Comment by gondar00** [comment]
Got it, would be nice to have a feature where the color changes or the name of the person shows up. 

But thanks for the clarification not a bug 

I'll close this issue
