### ISSUE TITLE
Zero-knowledge server

### ISSUE THREAD

**Issue by erdnaxe** [ekzhang/rustpad#45]
This is a feature request.

From a privacy point of view, it would be nice if the server could have no knowledge of the content.
Does the server need to know the content for real-time collaboration?
If zero-knowledge during edition is not possible, could it be possible when sharing a read-only version of the document?

[PrivateBin](https://privatebin.info/) (a zero-knowledge pastebin) is using the URL #hash after a GET parameter to store the key then some JavaScript to encode/decode it.

Thank you,

**Comment by ekzhang** [comment]
The server needs to have knowledge of the content for this centralized operational transformation to work. It uses the information to make sure that no clients go out-of-sync and resolve edit conflicts.

If you're looking for recent work in end-to-end encryption for collaborative editing using CRDTs, you can check out [Skiff](https://www.skiff.org/).

Disclaimer: Skiff is a commercial offering, but I am unaffiliated with them.
