### ISSUE TITLE
Support for authentication?

### ISSUE THREAD

**Issue by nojb** [ekzhang/rustpad#49]
Hello, thanks for your great work!

Would it be difficult to support some basic form of authentication? I am a bit wary of deploying Rustpad on a production server in case it could be abused and affect the rest of the services running on that server.

I guess one could implement authentication by running Rustpad behind a proxy, but I thought that perhaps something simple (eg Basic authentication) could be implemented directly inside Rustpad to avoid the extra complexity.

**Comment by ekzhang** [comment]
What kind of authentication mechanism would be useful? An SSH key? A password field within the web UI? User accounts?

I'm not sure if any of these are within scope.

**Comment by poVoq** [comment]
Basic LDAP support targeting LLDAP would be nice: https://github.com/nitnelave/lldap
