### ISSUE TITLE
Announcement: engineer-man/piston integration for code compilation/execution

### ISSUE THREAD

**Issue by gagbo** [ekzhang/rustpad#51]
Hello (using the issue tracker as a mailing list),

I've been looking for a replacement of the free trials of "online code interview tooling" to get both collaborative editing and the ability to compile/execute the common code. [Piston](https://github.com/engineer-man/piston) provides the ability to self host a multi-language code execution service with a unified API so I thought it was a nice fit.

Therefore I've been working on expanding the Client-Server protocol and adding an extra React component to integrate Piston code execution API to rustpad.

This picture has been done testing with the public instance of piston (`PISTON_URL=https://emkc.org/api/v2/piston cargo run`)
![image](https://user-images.githubusercontent.com/10496163/179421391-7ef5335f-d2b4-4ebb-b2a2-55ff553a81ad.png)

For the time being it's on a branch that I happily force-push https://git.sr.ht/~gagbo/rustpad/log/gagbo/piston-integration, but if there's interest I can take some design and coding review to clean everything up and try to get it merged here. Whatever gets decided it's a nice project for me to get into front-end development so I'll keep making dubious changes to the UI/UX.

**Comment by ekzhang** [comment]
Please don't use the Rustpad issue tracker as a mailing list. Thanks.
