### ISSUE TITLE
Non docker install?

### ISSUE THREAD

**Issue by ithakaa** [ekzhang/rustpad#52]
Do we have non docker install docs?

**Comment by ekzhang** [comment]
Unfortunately we only officially distribute the application as a container. You don't have to run it with Docker though; any OCI-compliant runtime will do the trick. And the container is only a couple MB.

We could distribute binaries as well, but they would have to keep track of the associated static HTML files next to the binary, which is kind of annoying. There's also the problem that building multi-platform binaries is kind of messy and requires cross-compilation to automate.

**Comment by ithakaa** [comment]
As a non programmer/ developer I would need a short readme to get it installed without docker

Is this something you can provide?

**Comment by ekzhang** [comment]
If you're on Linux, then the easiest way to get the files for Rustpad would be to just extract them from the Docker image. There are instructions for building from source in the README (and there's obviously the Dockerfile as well, which is pretty straightforward), but that would likely be harder.

You can do something like [this StackOverflow answer](https://stackoverflow.com/a/31316636/2514396).

```bash
id=$(docker create ekzhang/rustpad)
docker cp $id:/ rustpad
docker rm -v $id
```

Then just untar the file with `tar xf rustpad.tar`, and you'll have the `rustpad-server` binary and associated static files folder `dist`. You can ignore the rest of the files.

**Comment by ekzhang** [comment]
An alternative set of commands that doesn't depend on a running Docker daemon (uses OCI images directly instead) and doesn't generate the procfs junk that `docker cp` does:

```
sudo apt-get update
sudo apt-get -y install skopeo umoci
```

```
skopeo copy docker://ekzhang/rustpad oci:rustpad-layers:latest
mkdir rustpad && umoci raw unpack --rootless --image rustpad-layers:latest rustpad
rm -rf rustpad-layers
```

This generates:

```sh-session
$ ls -l rustpad
total 13688
drwxr-xr-x 3 ubuntu ubuntu     4096 Feb 19 15:55 dist
-rwxr-xr-x 1 ubuntu ubuntu 14010192 Feb 19 16:07 rustpad-server
```

**Comment by ithakaa** [comment]
And we can just execute the rust server?

**Comment by ithakaa** [comment]
skopeo is not found in the ubuntu 20.04 repo

**Comment by ekzhang** [comment]
It's in Ubuntu 22.04. You can find installation instructions on the skopeo repository. If you don't want to use skopeo, you can use any other container management tool.

Unfortunately I'm not able to provide technical support for all installation issues, please keep the issues tracker for bugs!
