### ISSUE TITLE
 Is it possible to run rustpad on redox-os?

### ISSUE THREAD

**Issue by codehangen** [ekzhang/rustpad#53]
Hi all! I like the redox-os operating system and the rustpad project, and I would like to know if it is possible to run rustpad on redox-os. 

1. A question does rustpad work on redox-os? 
2. Is it possible to run rustpad on redox-os? 

**Technical issue and not feature request.**

**Comment by ekzhang** [comment]
I'm not familiar with Redox OS and wouldn't be able to answer this question, unfortunately.
