### ISSUE TITLE
Support for Notion-like comments?

### ISSUE THREAD

**Issue by rattrayalex** [ekzhang/rustpad#54]
While collaborating on an idea that we are sketching out, it is often nice to be able to highlight a chunk of code on it and leave a comment (not a code comment) that can begin a discussion thread.

This would be a pretty major and potentially orthogonal feature, but might be pretty amazing for use-cases like design docs, demos, and potentially even coding interviews, where tools like Rustpad may be most useful.

Of course, this would mean a bunch of parallel metadata for each document, and could get quite tricky in general (what happens when someone edits the borders of a commented piece of code while someone else is commenting it?) so it might be too hard / too much work.

What do you think? Achievable? Something you'd be excited to do?

**Comment by ekzhang** [comment]
Not within scope for Rustpad but you're welcome to implement it on your own.
