### ISSUE TITLE
Collaborative editing of local file?

### ISSUE THREAD

**Issue by gregfr** [ekzhang/rustpad#65]
Greetings

This project looks amazing! I was wondering: can Rustpad be used for 2 people to collaboratively edit a file on the server, the people using only they web browser?
My goal is to allow CSS tweeking on the server.

Thanks in advance!

Regards

**Comment by gregfr** [comment]
I've tried to tap into the sqlite file, I can read from it, but in order for the Rustpad to load its content, I have to restart the container, isn't it? is there a way to trigger a reload of the file without restarting?

**Comment by ekzhang** [comment]
Hello! Yes, Rustpad allows 2 or more people to collaboratively edit a file from their web browser.

It's not possible to have Rustpad reload its document from the database, as then there may be concurrent modifications both from Rustpad itself and the database, and it would be ambiguous which one is the source of truth.
