### ISSUE TITLE
Spell Checking

### ISSUE THREAD

**Issue by abn0mad** [ekzhang/rustpad#67]
Hi there,

I've been searching for a way to enable (browser built-in) spell checking - to be able to use the LanguageTool extension in Rustpad, but I can't seem to find a way.

Couldn't find anything under F1 or shift-F10. Forcing spell check in about:config (Firefox) didn't do anything either.

Is there some way to enable browser spell checking – or could this be added as a feature?

**Comment by ekzhang** [comment]
No I don't believe so, it's intended to be a code editor so spell checking isn't built in.

**Comment by abn0mad** [comment]
@ekzhang - thanks for the reply :)

As Rustpad supports both markdown and plain text it would be a great lightweight alternative to Etherpad. Wouldn't it be possible somehow to enable the browser spell check plugin for those file types?

I was hoping to use Rustpad to edit markdown files, as a simple frontend for the HUGO site generator.

It seems that all Monaco based apps have this issue, it is the same with Gitea / Forgejo..

**Comment by ekzhang** [comment]
Interesting! Hmm, I just released a simpler and more minimal [collaborative editing server](https://github.com/ekzhang/cm-collab), and this one is based on CodeMirror 6, which supports the browser's native spell check if you just add:

```
EditorView.contentAttributes.of({ spellcheck: 'true' }),
```

I'm not sure what your goal is as a Hugo frontend, are you trying to create an application for users, or just for yourself? In either case I think this one will be easier to embed within a larger app than Rustpad.

**Comment by abn0mad** [comment]
Thanks for the prompt reply @ekzhang :))

Nice - cm-collab seems like a nice upcoming solution, especially after a dark mode has been added.

I'm not trying to make any larger application at the moment, at least not for this purpose. My main problem with HUGO is not having a nice Markdown editor that will allow me to use LanguageTool or Grammarly when writing posts. I exclusively run Linux, but haven't been able to find an offline editor that has LanguageTool support (save some very old and poorly maintained (Neo)ViM plugins that don't work very well). So far only Etherpad and Hedgedoc fit the bill more or less, but they are rather heavy and a bit overkill. Rustpad or Gitea would be great (the latter especially as the HUGO site is hosted on Gitea as well) - but both use Monaco, so spell-checking plugins are a no-go for now. 

After raising the issue here - I found [this](https://github.com/microsoft/monaco-editor/issues/1977) - this morning, so it seems the issue has been around for a while, but the Monaco devs aren't doing anything with it so far.

Your cm-collab project looks promising though :))

**Comment by ekzhang** [comment]
If you're looking for an _offline_ editor then I'm not sure either make that much sense as collaborative editors, maybe try StackEdit or any other solution.

My recent project was just a tech demo and not meant to be a full user application

**Comment by abn0mad** [comment]
@ekzhang - no, I just mentioned it as to show that I've explored both avenues, a collaborative editor would be best for sure, although at the moment any (lightweight) editor with some form of browser based spelling check plugin support would fit the bill. I think your cm-collab demo has potential too, it's a nice, minimalist and lightweight solution compared to Etherpad and HedgeDoc.

It would be great if Monaco would offer a browser based spelling check option on Markdown and plain text - so that Rustpad and Gitea could inherit the feature.

**Comment by ekzhang** [comment]
Thanks for the kind words!

Just to repeat:

> No I don't believe so, it's intended to be a code editor so spell checking isn't built in.

This feature is out-of-scope for Rustpad itself regardless of whether it's supported by Monaco, so I'm closing it now. If you want to write your own collaborative Markdown editor, I think I've provided you all the resources.

**Comment by abn0mad** [comment]
Fair enough, thanks for the replies and of course your hard work on Rustpad; a great tool - clean, performant and well-designed overall :)
