### ISSUE TITLE
URL constructor: rustpad_wasm_bg.wasm is not a valid URL.

### ISSUE THREAD

**Issue by jvasile** [ekzhang/rustpad#72]
Did a fresh clone, then:
```
wasm-pack build --target web rustpad-wasm
npm install
cargo run
npm run dev
```

At `localhost:3000`, I see the following error on the web console:

```
Uncaught (in promise) TypeError: URL constructor: rustpad_wasm_bg.wasm is not a valid URL.
    init rustpad_wasm.js:406
    <anonymous> index.tsx:9
[rustpad_wasm.js:406:16](http://localhost:3000/node_modules/rustpad-wasm/rustpad_wasm.js)
```

Nothing is displayed in the browser tab.

**Comment by ntninja** [comment]
This is most likely https://github.com/vitejs/vite/issues/8427

Updating to Vite 3 or 4 partially fixes the issue, but you need to manually run the following whenever it breaks in dev mode:

```shell
cp rustpad-wasm/pkg/rustpad_wasm_bg.wasm  node_modules/.vite/deps/
```

Release builds (`npm run build`) work with Vite 3 and 4 at least.

To switch to Vite 4 after checkout run:

```shell
npm add --save-dev "vite@4"
npm install
```

**Comment by ekzhang** [comment]
Thanks for figuring out this issue! I'll update the repository.

**Comment by ntninja** [comment]
Don’t worry, I have some more fixes. I’ll make a PR then.
