### ISSUE TITLE
Protocol documentation

### ISSUE THREAD

**Issue by jvasile** [ekzhang/rustpad#87]
It would be interesting to have documentation of the protocol so that somebody might create a desktop client or teach vim or emacs to talk to a Rustpad editing session.  Does this exist somewhere?  Thanks much.

**Comment by ekzhang** [comment]
The protocol is pretty simple, it's JSON over WebSocket. A good place to start would be these two structs in `rustpad.rs`.

https://github.com/ekzhang/rustpad/blob/cbc5df8b4b2914fa1f13e328b0acd7649985c723/rustpad-server/src/rustpad.rs#L59-L91

The structs are serialized with serde_json, and the only tricky part of this is the specific serialization format of `OperationSeq` — this is an array with positive, negative numbers for (retain, delete) and strings for inserted content.
