### ISSUE TITLE
Feature Request: Typst language support

### ISSUE THREAD

**Issue by MelihDarcanxyz** [ekzhang/rustpad#88]
Hi, first of all, thanks for this software.

Typst is a great tool for paper / thesis / article or just homework composing, like LaTeX. It has a VSCode plugin support too. It would be nice to be able to compose papers together with other authors using rustpad.

Have a nice day!

**Comment by ekzhang** [comment]
Rustpad is a general editor, and Typst looks like it [already has collaborative editing support](https://typst.app/), so we probably won't add this.
